### ISSUE TITLE
没有钟离不开盾角色打地脉死亡开始转圈有问题可以增加四星角色护盾吗？

### ISSUE THREAD

**Issue by QJKG** [tignioj/minimap#18]

**Comment by tignioj** [comment]
请阅读说明文档

> 开盾：到达该点位后开启护盾。需要队伍中有护盾角色之一(钟离、莱依拉、迪奥娜、诺艾尔、绮良良)

不生效还是什么问题？什么叫开始转圈？

**Comment by QJKG** [comment]
不是对应角色转圈 我猜转圈的是纳西达 队伍当中根据提示配置好了队伍但是过去打地脉死亡就不是对应角色开始转圈了
