### ISSUE TITLE
GPU版本支持a卡吗

### ISSUE THREAD

**Issue by yehuoshun** [tignioj/minimap#3]
我使用的是A卡

**Comment by tignioj** [comment]
你可以参考paddleocr的安装方式，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html 

它的GPU加速依赖于cuda，A卡似乎不行，考虑到兼容性问题我关掉了GPU，那个东西可能不好打包。切换成CPU后，由于开销比较大，我降低了调用频率，暂时也够用了。
