### ISSUE TITLE
闪退报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by tignioj** [tignioj/minimap#4]
https://www.zhihu.com/question/40390548

把计算机名称改成英文

设置->系统->系统信息->重命名此电脑：修改为英文

**Comment by huiyadanli** [comment]
https://github.com/python/cpython/issues/70415

升级 py 至v3.9.20 以上版本应该能够解决这个问题

**Comment by tignioj** [comment]
升级到3.10.12，解决了
